AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  ProjectName:
    Type: String
    Default: PublicIpLister
  PublicIpListenerVersion:
    Type: String
    Default: 1.0.6

Resources:

  Bucket:
    Type: AWS::S3::Bucket

  Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: PublicIpListener
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: codebuild
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - !Sub "arn:aws:logs:*:${AWS::AccountId}:log-group:/aws/codebuild/${ProjectName}"
                  - !Sub "arn:aws:logs:*:${AWS::AccountId}:log-group:/aws/codebuild/${ProjectName}:*"
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:GetBucketAcl
                  - s3:GetBucketLocation
                Resource:
                  - !Sub "arn:aws:s3:::codepipeline-*"
              - Effect: Allow
                Action:
                  - s3:*
                Resource:
                  - !GetAtt Bucket.Arn
                  - !Sub "${Bucket.Arn}/*"
        - PolicyName: library-needs
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - apigateway:GET
                  - cloudfront:ListDistributions
                  - ec2:DescribeInstances
                  - elasticloadbalancing:DescribeLoadBalancers
                  - lightsail:GetInstances
                  - lightsail:GetLoadBalancers
                  - rds:DescribeDBInstances
                  - redshift:DescribeClusters
                  - es:ListDomainNames
                Resource: "*"

  Project:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Ref ProjectName
      ServiceRole: !GetAtt Role.Arn
      Environment:
        Type: linuxContainer
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/ruby:2.5.3
        EnvironmentVariables:
          - Name: PUBLIC_IP_LISTENER_VERSION
            Type: PLAINTEXT
            Value: !Ref PublicIpListenerVersion
          - Name: ACCOUNT_ID
            Type: PLAINTEXT
            Value: !Sub "${AWS::AccountId}"
          - Name: REGIONS
            Type: PLAINTEXT
            Value: |
              eu-west-1 eu-west-2 eu-west-3
              us-east-1 us-west-1
      Source:
        Type: NO_SOURCE
        BuildSpec: |
          version: 0.2
          phases:
            install:
              commands:
                - gem install aws_public_ips -v ${PUBLIC_IP_LISTENER_VERSION}
            build:
              commands:
                - for i in $REGIONS; do AWS_REGION=$i aws_public_ips -f prettyjson > results-$ACCOUNT_ID-$i.json; done
          artifacts:
            files: '*'
      Artifacts:
        Type: S3
        Location: !Ref Bucket
        Name: Results
        Path: !Sub "${AWS::AccountId}"
      TimeoutInMinutes: 60